# Generated by Django 5.1.3 on 2024-12-08 20:39

import django.contrib.postgres.fields
import django.db.models.deletion
import forcedfun.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.SlugField()),
                (
                    "users",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL, blank=True),
                ),
            ],
            options={
                "default_related_name": "games",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "options",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), max_length=2, size=None
                    ),
                ),
                ("answer_idx", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "answer_text",
                    forcedfun.models.TextInputTextField(blank=True, default=""),
                ),
                ("points", models.PositiveSmallIntegerField()),
                (
                    "scored_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="forcedfun.game",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "default_related_name": "questions",
            },
        ),
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("option_text", forcedfun.models.TextInputTextField()),
                ("option_idx", models.PositiveSmallIntegerField()),
                ("points", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="forcedfun.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "selections",
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="game_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="selection",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="selection_user_question_unique"
            ),
        ),
    ]
