name: test

on:
  pull_request:
    branches:
      - main


jobs:
  test:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: forcedfun
          POSTGRES_DB: forcedfun
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Run tests
        run: |
          make installci
          make mypy
          make fmtci
          make covci